### ISSUE TITLE
Browserify options usage is not clear enough

### ISSUE THREAD

**Issue by GabiGrin** [wallabyjs/wallaby-browserify-sample#2]
Hey,
I need to pass both options and use the browserify instance to chain transformers.
The sample here feels over-simplified, and is the same code that is on the documentation.
Is it possible to include a more realistic usage example? with both options and transformers?

Thanks

**Comment by ArtemGovorov** [comment]
You may [pass options here](https://github.com/wallabyjs/wallaby-browserify-sample/blob/master/wallaby.js#L4), and you may just uncomment [this line of code to get and use browserify instance](https://github.com/wallabyjs/wallaby-browserify-sample/blob/master/wallaby.js#L8) (it uses `babelify` transform in the example). Does it address your question?

**Comment by GabiGrin** [comment]
Oh I missed the comma there, so I wasn't sure how to pass the function. That helps, yes.
Thanks!
